name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
      id: go

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download dependencies
      run: |
        go mod download
        go mod verify

    - name: Build
      run: go build -o proxy ./pkg